# Blog info
blog_name: liuzhen blog
slogan: 为一桩事业呕心沥血，为一种梦想至死不渝
url: http://localhost:4000

# Set avatar (Absolute url and relative url)
avatar: /images/avatar.jpg

# Set favicon
favicon: /favicon.ico

# For seo
keywords: 笑看人生,刘振,前端,前端开发,nodejs,JavaScript,java,mysql,mongodb,nginx,linux,apache,php,centos,oracle

home_nav:
  - name: blog
    url: /archives
    target_blank: false #不在新页面打开
  - name: Project
    url: /project/
    target_blank: true #在新页面打开

# config page nav
page_nav:
  - name: 博客
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: 分类
    url: /category/
    target_blank: false
  - name: 标签
    url: /tag/
    target_blank: false
  - name: 友链
    url: /link/
    target_blank: false
  - name: 关于
    url: /about/
    target_blank: false
  - name: 搜索
    url: /search/
    target_blank: false # 在新页面打开

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|fase

# 盒子
toolbox:
  isShow: true # true|fase
  text: 盒子

search_slogan:
  isShow: true # true|fase
  text: Can you find the bug of world ~

link_slogan:
  isShow: true # true|fase
  text: 交换友链可以邮件 liuzhenlife#163.com


# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

donation:
  show: true
  btn_text: 支持一下
  tip: 扫一扫，支持 博主-刘振
  items:
    - type: 微信
      text: 微信扫一扫
      imgUrl: /images/qr-wechat.png
    - type: 支付宝
      text: 支付宝扫一扫
      imgUrl: /images/qr-alipay.png




post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true
  open_in_new_window: false
  show_prev_next: true

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style, 推荐把样式文件放在blog源码文件夹，而不是主题里面
personal_style: /css/personal-style.css

# 这个值取决于你得背景图片是深色还是浅色，深色用dark，浅色用light
home_background_scheme: light # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST


# =========================================================
# 第三方服务
# =========================================================
# Stats
google_analytics:
baidu_analytics:

# Comment service
# hypercomments_id: 89821
# gentie_key: d16a7241e7cd4b389584ed8db2a4e8bc

# 文章访问量统计和显示
liuzhentongji: true

# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "刘振，1991."
    - "软件工程师"
  #- type: Github
  #  icon: icon-github
  #  text_key: Github
  #  text_value: "@forsigner"
  #  text_value_url: https://github.com/forsigner
  #- type: weibo
  #  icon: icon-weibo
  #  text_key: 微博
  #  text_value: "@forsigner"
  #  text_value_url: http://weibo.com/u/1847075964
  - type: mail
    icon: icon-mail
    text_key: Email
    text_value: "liuzhenlife#163.com"
  - type: location
    icon: icon-location
    text_value: 北京

link:
  - name: 北京雷铭智信科技有限公司
    info: 雷铭电子商务系统提供企业级的Java电子商务解决方案，为全国中小企业提供PC,APP,微信商城一站式全套产品，做到四网合一,满足广大企业及开发商电子商务发展需求及定制开发需求。
    url: http://www.leimingtech.com
    avatar: http://www.leimingtech.com/resource/images/lmlogo.png

project:
  - type: personal
    name: B2B2C商城
    url: http://www.leimingtech.com
    intro: 雷铭电子商务系统提供企业级的Java电子商务解决方案，为全国中小企业提供PC,APP,微信商城一站式全套产品，做到四网合一,满足广大企业及开发商电子商务发展需求及定制开发需求。
  - type: company
    name: CMS内容管理系统
    url: http://www.leimingtech.com
    intro: 雷铭网站群内容管理系统提供企业级的内容管理解决方案，为新闻媒体,企事业单位提供站群版PC,APP,微网站一站式全套产品，做到四网合一,满足广大企业及开发商网站群需求及定制开发需求。